export const PHOTOS_ACTION = {
  FETCH_MEDIA_LIST_REQUEST: 'FETCH_MEDIA_LIST_REQUEST',
  FETCH_MEDIA_LIST: 'FETCH_MEDIA_LIST',
  FETCH_MEDIA_LIST_SUCCESS: 'FETCH_MEDIA_LIST_SUCCESS',
  FETCH_MEDIA_LIST_FAILURE: 'FETCH_MEDIA_LIST_FAILURE'
};

